import { NextRequest, NextResponse } from "next/server";
import { getFourWeeklyReview } from "@/app/actions/reports";
import { requireUser } from "@/lib/requireUser";
import { getServerSupabase } from "@/lib/supabaseServer";

export const runtime = "nodejs";

type FourWeekSummary = Awaited<ReturnType<typeof getFourWeeklyReview>>;
type Tone = "good" | "warn" | "bad" | "neutral";

const PAGE_W = 595;
const PAGE_H = 842;
const M = 42;
const CONTENT_W = PAGE_W - M * 2;

function esc(input: unknown) {
  return String(input ?? "")
    .replace(/[^\x20-\x7E]/g, (ch) => {
      if (ch === "£") return "GBP ";
      if (ch === "°") return " deg";
      if (ch === "–" || ch === "—") return "-";
      if (ch === "•") return "-";
      return "";
    })
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");
}

function ukDate(iso: string | null | undefined) {
  if (!iso) return "-";
  const raw = String(iso).slice(0, 10);
  const [y, m, d] = raw.split("-");
  if (!y || !m || !d) return raw;
  return `${d}/${m}/${y}`;
}

function pct(done: number, total: number | null | undefined) {
  if (!total) return "0%";
  return `${Math.round((done / total) * 1000) / 10}%`;
}

function wrapText(text: string, maxChars: number) {
  const words = esc(text).split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let line = "";

  for (const word of words) {
    const next = line ? `${line} ${word}` : word;
    if (next.length > maxChars && line) {
      lines.push(line);
      line = word;
    } else {
      line = next;
    }
  }

  if (line) lines.push(line);
  return lines.length ? lines : ["-"];
}

function overallStatus(summary: FourWeekSummary) {
  let score = 0;
  if (summary.tempFails > 0) score += 2;
  if ((summary.cleaningTotal ?? 0) > summary.cleaningDone) score += 2;
  if (summary.trainingOver > 0) score += 2;
  if (summary.allergenOver > 0) score += 2;
  if ((summary.signoffsExpected ?? 0) > summary.signoffsDone) score += 1;
  if (summary.incidents > 0) score += 1;
  if (summary.calibrationDue) score += 1;

  if (score >= 6) return "ACTION REQUIRED";
  if (score >= 3) return "NEEDS ATTENTION";
  return "ON TRACK";
}

async function getLocationLabel(locationId: string | null | undefined) {
  if (!locationId) return "Organisation report";

  const sb = await getServerSupabase();

  const {
    data: { user },
    error: userErr,
  } = await sb.auth.getUser();

  if (userErr || !user) return "Location report";

  const { data: profile } = await sb
    .from("profiles")
    .select("org_id")
    .eq("id", user.id)
    .maybeSingle();

  const orgId = profile?.org_id ? String(profile.org_id) : null;
  if (!orgId) return "Location report";

  const { data: location } = await sb
    .from("locations")
    .select("name")
    .eq("id", locationId)
    .eq("org_id", orgId)
    .maybeSingle();

  return location?.name ? `Location: ${location.name}` : "Location report";
}

class Pdf {
  pages: string[] = [];
  current: string[] = [];
  y = PAGE_H - M;

  addRaw(s: string) {
    this.current.push(s);
  }

  newPage() {
    if (this.current.length) this.pages.push(this.current.join("\n"));
    this.current = [];
    this.header();
  }

  ensure(space: number) {
    if (this.y - space < 74) this.newPage();
  }

  rgb(r: number, g: number, b: number) {
    this.addRaw(`${r} ${g} ${b} rg`);
    this.addRaw(`${r} ${g} ${b} RG`);
  }

  rect(x: number, y: number, w: number, h: number, fill = true) {
    this.addRaw(`${x} ${y} ${w} ${h} re ${fill ? "f" : "S"}`);
  }

  text(
    value: string,
    x: number,
    y: number,
    size = 10,
    font: "F1" | "F2" = "F1",
    colour: [number, number, number] = [0.1, 0.12, 0.16]
  ) {
    this.rgb(...colour);
    this.addRaw(`BT /${font} ${size} Tf 1 0 0 1 ${x} ${y} Tm (${esc(value)}) Tj ET`);
  }

  line(
    x1: number,
    y1: number,
    x2: number,
    y2: number,
    colour: [number, number, number] = [0.82, 0.86, 0.91]
  ) {
    this.rgb(...colour);
    this.addRaw(`${x1} ${y1} m ${x2} ${y2} l S`);
  }

  header() {
    this.y = PAGE_H - M;
    this.text("TempTake", M, PAGE_H - 34, 12, "F2", [0.02, 0.42, 0.32]);
    this.text("Four-weekly food safety review", M + 78, PAGE_H - 34, 9.5, "F1", [
      0.35, 0.39, 0.46,
    ]);
    this.line(M, PAGE_H - 48, PAGE_W - M, PAGE_H - 48);
    this.y = PAGE_H - 72;
  }

  footer(pageNo: number, totalPages: number) {
    this.line(M, 44, PAGE_W - M, 44);
    this.text("Generated by TempTake", M, 28, 8, "F1", [0.45, 0.49, 0.56]);
    this.text(`Page ${pageNo} of ${totalPages}`, PAGE_W - M - 70, 28, 8, "F1", [
      0.45, 0.49, 0.56,
    ]);
  }

  title(title: string, subtitle: string) {
    this.ensure(70);
    this.text(title, M, this.y, 20, "F2", [0.02, 0.06, 0.14]);
    this.y -= 18;
    this.text(subtitle, M, this.y, 10, "F1", [0.35, 0.39, 0.46]);
    this.y -= 24;
  }

  section(title: string, subtitle?: string) {
    this.ensure(subtitle ? 62 : 46);
    this.y -= 8;
    this.text(title, M, this.y, 13, "F2", [0.02, 0.06, 0.14]);
    this.y -= 8;
    this.line(M, this.y, PAGE_W - M, this.y, [0.78, 0.84, 0.9]);
    this.y -= 14;

    if (subtitle) {
      for (const line of wrapText(subtitle, 94).slice(0, 2)) {
        this.text(line, M, this.y, 8.5, "F1", [0.45, 0.49, 0.56]);
        this.y -= 12;
      }
      this.y -= 2;
    }
  }

  paragraph(text: string) {
    const lines = wrapText(text, 94);
    this.ensure(lines.length * 13 + 8);
    for (const line of lines) {
      this.text(line, M, this.y, 9.5);
      this.y -= 13;
    }
    this.y -= 4;
  }

  bullet(text: string) {
    const lines = wrapText(text, 88);
    this.ensure(lines.length * 13 + 5);
    this.text("-", M, this.y, 10, "F2");
    this.text(lines[0] ?? "", M + 12, this.y, 9.5);
    this.y -= 13;

    for (const line of lines.slice(1)) {
      this.text(line, M + 12, this.y, 9.5);
      this.y -= 13;
    }

    this.y -= 1;
  }

  empty(message = "No records found.") {
    this.ensure(30);
    this.rgb(0.97, 0.98, 0.99);
    this.rect(M, this.y - 26, CONTENT_W, 26);
    this.text(message, M + 8, this.y - 17, 9, "F1", [0.45, 0.49, 0.56]);
    this.y -= 36;
  }

  card(
    x: number,
    y: number,
    w: number,
    h: number,
    label: string,
    value: string,
    note: string,
    tone: Tone
  ) {
    const bg =
      tone === "good"
        ? [0.9, 0.98, 0.94]
        : tone === "warn"
        ? [1, 0.97, 0.88]
        : tone === "bad"
        ? [1, 0.92, 0.92]
        : [0.96, 0.97, 0.99];

    const accent =
      tone === "good"
        ? [0.05, 0.65, 0.38]
        : tone === "warn"
        ? [0.86, 0.49, 0.05]
        : tone === "bad"
        ? [0.85, 0.14, 0.14]
        : [0.45, 0.49, 0.56];

    this.rgb(bg[0], bg[1], bg[2]);
    this.rect(x, y - h, w, h);
    this.rgb(accent[0], accent[1], accent[2]);
    this.rect(x, y - h, 4, h);

    this.text(label.toUpperCase(), x + 12, y - 17, 7.4, "F2", [
      0.35, 0.39, 0.46,
    ]);
    this.text(value, x + 12, y - 42, value.length > 12 ? 12 : 18, "F2", [
      0.02, 0.06, 0.14,
    ]);
    this.text(note, x + 12, y - 60, 8, "F1", [0.35, 0.39, 0.46]);
  }

  metricGrid(
    items: Array<{
      label: string;
      value: string;
      note: string;
      tone: Tone;
    }>
  ) {
    this.ensure(170);
    const gap = 10;
    const w = (CONTENT_W - gap * 3) / 4;
    const h = 78;

    let x = M;
    let y = this.y;

    items.forEach((item, i) => {
      this.card(x, y, w, h, item.label, item.value, item.note, item.tone);
      x += w + gap;

      if ((i + 1) % 4 === 0 && i !== items.length - 1) {
        x = M;
        y -= h + gap;
      }
    });

    this.y = y - h - 22;
  }

  table(headers: string[], rows: string[][], widths: number[]) {
    if (!rows.length) {
      this.empty();
      return;
    }

    const headerH = 24;
    const lineH = 11;
    const padY = 8;

    const drawHeader = () => {
      this.ensure(headerH + 24);
      this.rgb(0.94, 0.97, 0.98);
      this.rect(M, this.y - headerH, CONTENT_W, headerH);

      let x = M + 6;
      headers.forEach((h, i) => {
        this.text(h, x, this.y - 16, 8, "F2", [0.35, 0.39, 0.46]);
        x += widths[i];
      });

      this.y -= headerH;
    };

    drawHeader();

    for (const row of rows) {
      const wrapped = row.map((cell, i) =>
        wrapText(cell ?? "-", Math.max(8, Math.floor(widths[i] / 5.3))).slice(0, 3)
      );

      const linesCount = Math.max(...wrapped.map((x) => x.length), 1);
      const rowH = Math.max(26, linesCount * lineH + padY * 2);

      if (this.y - rowH < 74) {
        this.newPage();
        drawHeader();
      }

      this.line(M, this.y, PAGE_W - M, this.y, [0.9, 0.92, 0.95]);

      let cx = M + 6;
      wrapped.forEach((cellLines, i) => {
        let ty = this.y - 15;
        for (const line of cellLines) {
          this.text(line, cx, ty, 8.2);
          ty -= lineH;
        }
        cx += widths[i];
      });

      this.y -= rowH;
    }

    this.y -= 10;
  }

  finish() {
    if (this.current.length) this.pages.push(this.current.join("\n"));

    const totalPages = this.pages.length;

    const finalPages = this.pages.map((content, i) => {
      const footerDoc = new Pdf();
      footerDoc.current = [content];
      footerDoc.footer(i + 1, totalPages);
      return footerDoc.current.join("\n");
    });

    const objects: string[] = [];
    const catalog = 1;
    const pagesObj = 2;
    const fontRegular = 3;
    const fontBold = 4;

    const pageObjs: number[] = [];
    const contentObjs: number[] = [];

    let next = 5;
    finalPages.forEach(() => {
      pageObjs.push(next++);
      contentObjs.push(next++);
    });

    objects[catalog] = `<< /Type /Catalog /Pages ${pagesObj} 0 R >>`;
    objects[pagesObj] = `<< /Type /Pages /Kids [${pageObjs
      .map((n) => `${n} 0 R`)
      .join(" ")}] /Count ${pageObjs.length} >>`;
    objects[fontRegular] = `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`;
    objects[fontBold] = `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>`;

    finalPages.forEach((content, i) => {
      const p = pageObjs[i];
      const c = contentObjs[i];
      const len = Buffer.byteLength(content, "utf8");

      objects[p] = `<< /Type /Page /Parent ${pagesObj} 0 R /MediaBox [0 0 ${PAGE_W} ${PAGE_H}] /Resources << /Font << /F1 ${fontRegular} 0 R /F2 ${fontBold} 0 R >> >> /Contents ${c} 0 R >>`;
      objects[c] = `<< /Length ${len} >>\nstream\n${content}\nendstream`;
    });

    let pdf = "%PDF-1.4\n";
    const offsets: number[] = [0];

    for (let i = 1; i < objects.length; i++) {
      offsets[i] = Buffer.byteLength(pdf, "utf8");
      pdf += `${i} 0 obj\n${objects[i]}\nendobj\n`;
    }

    const xref = Buffer.byteLength(pdf, "utf8");
    pdf += `xref\n0 ${objects.length}\n0000000000 65535 f \n`;

    for (let i = 1; i < objects.length; i++) {
      pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
    }

    pdf += `trailer\n<< /Size ${objects.length} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;

    return Buffer.from(pdf, "utf8");
  }
}

function buildPdf(summary: FourWeekSummary, reportScopeLabel: string) {
  const pdf = new Pdf();
  pdf.newPage();

  const overall = overallStatus(summary);
  const compliantPct = pct(summary.compliantDays, summary.totalDays);
  const cleaningPct = pct(summary.cleaningDone, summary.cleaningTotal);
  const signoffPct = pct(summary.signoffsDone, summary.signoffsExpected);

  pdf.title(
    "Four-Weekly Food Safety Review",
    `${ukDate(summary.period.from)} to ${ukDate(summary.period.to)} | ${
      summary.period.days
    } review days | ${reportScopeLabel}`
  );

  pdf.metricGrid([
    {
      label: "Overall",
      value: overall,
      note: "Management status",
      tone: overall === "ON TRACK" ? "good" : overall === "NEEDS ATTENTION" ? "warn" : "bad",
    },
    {
      label: "Compliant days",
      value: compliantPct,
      note: `${summary.compliantDays}/${summary.totalDays} days`,
      tone: summary.compliantDays === summary.totalDays ? "good" : "warn",
    },
    {
      label: "Temps",
      value: String(summary.tempLogs),
      note: `${summary.tempFails} failed`,
      tone: summary.tempFails === 0 ? "good" : summary.tempFails <= 3 ? "warn" : "bad",
    },
    {
      label: "Cleaning",
      value: cleaningPct,
      note: `${summary.cleaningDone}/${summary.cleaningTotal ?? "-"} done`,
      tone:
        !summary.cleaningTotal || summary.cleaningDone >= summary.cleaningTotal
          ? "good"
          : "warn",
    },
    {
      label: "Sign-offs",
      value: signoffPct,
      note: `${summary.signoffsDone}/${summary.signoffsExpected ?? "-"} recorded`,
      tone:
        summary.signoffsExpected == null || summary.signoffsDone >= summary.signoffsExpected
          ? "good"
          : "warn",
    },
    {
      label: "Training",
      value: String(summary.trainingOver),
      note: `${summary.trainingDueSoon} due soon`,
      tone: summary.trainingOver > 0 ? "bad" : summary.trainingDueSoon > 0 ? "warn" : "good",
    },
    {
      label: "Allergens",
      value: String(summary.allergenOver),
      note: `${summary.allergenDueSoon} due soon`,
      tone: summary.allergenOver > 0 ? "bad" : summary.allergenDueSoon > 0 ? "warn" : "good",
    },
    {
      label: "Incidents",
      value: String(summary.incidents),
      note: "Logged incidents",
      tone: summary.incidents === 0 ? "good" : summary.incidents <= 2 ? "warn" : "bad",
    },
  ]);

  pdf.section("Inspector-ready summary", "The key evidence position for this four-week review.");
  pdf.bullet(`Report scope: ${reportScopeLabel}.`);
  pdf.bullet(`Temperature checks: ${summary.tempLogs} logged, ${summary.tempFails} failed.`);
  pdf.bullet(
    `Cleaning tasks: ${summary.cleaning.dueTotal} due, ${summary.cleaning.completedTotal} completed, ${summary.cleaning.missedTotal} missed.`
  );
  pdf.bullet(`Daily sign-offs: ${summary.signoffsDone}/${summary.signoffsExpected ?? "-"} recorded.`);
  pdf.bullet(
    `Training: ${summary.trainingOver} expired, ${summary.trainingDueSoon} due soon, ${summary.trainingAssigned} assigned, ${summary.trainingInProgress} in progress.`
  );
  pdf.bullet(`Allergens: ${summary.allergenOver} overdue, ${summary.allergenDueSoon} due soon.`);
  pdf.bullet(
    `Manager QC: ${summary.managerQcReviews} review(s)${
      summary.managerQcAverage != null ? `, average ${summary.managerQcAverage}/5` : ""
    }.`
  );

  pdf.section("Management actions", "Actions generated from repeated issues and missing evidence.");
  for (const rec of summary.recommendations.slice(0, 10)) pdf.bullet(rec);

  pdf.section("Priority issues");
  pdf.table(
    ["Issue", "Count", "Priority"],
    summary.topIssues.slice(0, 10).map((x) => [
      x.label,
      String(x.count),
      x.tone === "bad" ? "High" : x.tone === "warn" ? "Watch" : "Info",
    ]),
    [320, 70, 120]
  );

  pdf.section("Temperature review", "Failed checks, repeated patterns and corrective action evidence.");
  pdf.table(
    ["Area", "Item", "Fails", "Last seen"],
    summary.temperature.repeatFailures.slice(0, 12).map((x) => [
      x.area || "-",
      x.item || "-",
      String(x.count),
      ukDate(x.lastSeenOn),
    ]),
    [130, 220, 60, 100]
  );

  pdf.table(
    ["Failure detail", "Corrective action"],
    summary.temperature.recentFailures.slice(0, 10).map((x) => [
      x.details ?? "-",
      x.correctiveAction ?? "Missing / not recorded",
    ]),
    [255, 255]
  );

  pdf.section("Cleaning review", "Scheduled cleaning completed, missed and repeated.");
  pdf.table(
    ["Category", "Done", "Total", "Completion"],
    summary.cleaning.categoryProgress.slice(0, 12).map((x) => [
      x.category,
      String(x.done),
      String(x.total),
      pct(x.done, x.total),
    ]),
    [240, 80, 80, 110]
  );

  pdf.table(
    ["Repeated missed task", "Area/category", "Missed", "Last missed"],
    summary.cleaning.repeatMisses.slice(0, 12).map((x) => [
      x.task,
      [x.area, x.category].filter(Boolean).join(" / ") || "-",
      String(x.missedCount),
      ukDate(x.lastMissedOn),
    ]),
    [210, 150, 70, 80]
  );

  pdf.section("Training review", "Expired and upcoming training risk.");
  pdf.table(
    ["Staff", "Training", "Expires", "Status"],
    summary.training.drift.slice(0, 15).map((x) => [
      x.staffInitials ? `${x.staffName} (${x.staffInitials})` : x.staffName,
      x.type,
      ukDate(x.expiresOn),
      x.status === "expired" ? "Expired" : `Due in ${x.daysLeft}d`,
    ]),
    [170, 180, 80, 80]
  );

  pdf.section("Allergen review", "Review dates and next-due position.");
  pdf.table(
    ["Reviewed", "Next due", "Days", "Reviewer"],
    summary.allergens.recentReviews.slice(0, 10).map((x) => [
      ukDate(x.reviewedOn),
      ukDate(x.nextDue),
      x.daysUntil == null ? "-" : `${x.daysUntil}d`,
      x.reviewer ?? "-",
    ]),
    [110, 110, 80, 210]
  );

  pdf.section("Incidents and corrective actions", "Manual incidents logged during the period.");
  pdf.table(
    ["Date", "Type", "Details", "Immediate action"],
    summary.incidentsLog.recent.slice(0, 10).map((x) => [
      ukDate(x.happenedOn),
      x.type ?? "Incident",
      x.details ?? "-",
      x.immediateAction ?? "-",
    ]),
    [80, 100, 180, 150]
  );

  pdf.section("Sign-offs", "Daily management review evidence.");
  pdf.table(
    ["Date", "Signed by", "Notes"],
    summary.signoffs.recent.slice(0, 12).map((x) => [
      ukDate(x.signoffOn),
      x.signedBy ?? "-",
      x.notes ?? "-",
    ]),
    [90, 100, 320]
  );

  pdf.section("Manager QC and staffing", "Review activity and staff absence overlap.");
  pdf.table(
    ["Date", "Staff", "Reviewer", "Score", "Notes"],
    summary.managerQc.recent.slice(0, 10).map((x) => [
      ukDate(x.reviewedOn),
      x.staffInitials ? `${x.staffName} (${x.staffInitials})` : x.staffName,
      x.reviewer ?? "-",
      `${x.rating}/5`,
      x.notes ?? "-",
    ]),
    [70, 140, 90, 60, 150]
  );

  pdf.table(
    ["Staff", "Type", "Dates", "Status"],
    summary.staffAbsences.recent.slice(0, 10).map((x) => [
      x.teamMemberInitials ? `${x.teamMemberName} (${x.teamMemberInitials})` : x.teamMemberName,
      x.absenceType ?? "Absence",
      `${ukDate(x.startDate)} to ${ukDate(x.endDate)}`,
      x.status ?? "-",
    ]),
    [150, 110, 150, 100]
  );

  pdf.section("Calibration and hygiene rating", "Equipment verification and external hygiene record.");
  pdf.bullet(
    summary.calibration.due
      ? "Calibration review is currently due."
      : "Calibration review appears up to date."
  );
  pdf.bullet(`${summary.calibration.total} calibration check(s) logged in the review period.`);

  if (summary.hygiene.latest) {
    pdf.bullet(`Latest food hygiene rating: ${summary.hygiene.latest.rating ?? "-"}/5.`);
    pdf.bullet(`Inspection date: ${ukDate(summary.hygiene.latest.visitDate)}.`);
    if (summary.hygiene.latest.issuingAuthority) {
      pdf.bullet(`Issuing authority: ${summary.hygiene.latest.issuingAuthority}.`);
    }
  } else {
    pdf.bullet("No food hygiene rating record is available for this location.");
  }

  pdf.ensure(110);
  pdf.section("Review note");
  pdf.paragraph(
    "This report supports the regular four-weekly food safety review. It highlights recurring issues, missing evidence and management follow-up actions. It should be reviewed, acted on where required, and retained with the food safety records."
  );

  return pdf.finish();
}

export async function GET(req: NextRequest) {
  try {
    await requireUser();

    const { searchParams } = new URL(req.url);

    const to = searchParams.get("to") ?? undefined;
    const locationId = searchParams.get("locationId") ?? undefined;
    const download = searchParams.get("download");

    const summary = await getFourWeeklyReview({
      to,
      locationId,
    });

    const reportScopeLabel = await getLocationLabel(locationId);
    const pdfBytes = buildPdf(summary, reportScopeLabel);

    const filename = `four-weekly-review_${summary.period.from}_to_${summary.period.to}.pdf`;

    return new NextResponse(new Uint8Array(pdfBytes), {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Length": String(pdfBytes.length),
        "Content-Disposition":
          download === "1"
            ? `attachment; filename="${filename}"`
            : `inline; filename="${filename}"`,
        "Cache-Control": "no-store, no-cache, must-revalidate",
      },
    });
  } catch (error: any) {
    console.error("four-week pdf route error", error);

    return NextResponse.json(
      {
        error: error?.message ?? "Failed to generate four-week review PDF.",
      },
      { status: 500 }
    );
  }
}